-- Initial schema for local/CI Supabase (tables, RLS, functions, grants).
-- Source: staging public schema dump, Aug/Sep 2026.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

CREATE TABLE public.people (
  "Auto ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Created At" timestamptz,
  "Updated At" timestamptz,
  "Id" bigint,
  "Referral Source" text,
  "Equality Opt Out" jsonb,
  "Gender" text,
  "Town" text,
  "Postcode" text,
  "Other Support" text,
  "Marketing Opt Out" boolean,
  "FirstName" text,
  "LastName" text,
  "DateOfBirth" text,
  "Phone" text,
  "Email" text,
  "UniqueId" text,
  "OtherInfo" text,
  "Religion" text,
  "Ethnic Origin" text,
  "Sexual Orientation" text,
  "Marital Status" text,
  "Carer" boolean,
  "Disability" boolean,
  "Joined Date" text,
  "Acupuncture Data" boolean,
  "Haemophilia" boolean,
  "Pregnant" boolean,
  "Give Blood" boolean,
  "Signed" boolean,
  "Full Name" text,
  "Epilepsy" boolean,
  "Pacemaker" boolean,
  "ClientAgreementSigned" boolean
);

CREATE TABLE public.service (
  "Auto ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" text,
  "Is Current" boolean,
  "Created At" timestamptz,
  "Updated At" timestamptz,
  "Multi" boolean
);

CREATE TABLE public.attendance (
  "Date" date,
  "Person Id" bigint REFERENCES public.people ("Auto ID"),
  "Person Name" text,
  "ServiceName" text,
  "Auto ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Created At" timestamptz,
  "Updated At" timestamptz,
  "TotalAttendees" numeric DEFAULT 1,
  "Multi" boolean
);

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  updated_at timestamptz,
  username text,
  full_name text,
  avatar_url text,
  website text,
  "isAdmin" text
);

-- ---------------------------------------------------------------------------
-- Functions + auth trigger
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_people_auto_id_seq()
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  new_val bigint;
BEGIN
  SELECT COALESCE(MAX("Auto ID"), 1) INTO new_val FROM people;
  RETURN setval(pg_get_serial_sequence('people', 'Auto ID'), new_val, true);
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.people ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable insert for authenticated users only"
  ON public.people
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Enable all for authenticated users only"
  ON public.attendance
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Enable all for authenticated users only"
  ON public.service
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Users can select own profile"
  ON public.profiles
  FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile without elevating admin"
  ON public.profiles
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (
    (auth.uid() = id)
    AND (
      NOT (
        COALESCE("isAdmin", ''::text)
        IS DISTINCT FROM
        COALESCE(
          (SELECT p."isAdmin" FROM public.profiles p WHERE p.id = auth.uid()),
          ''::text
        )
      )
    )
  );

-- ---------------------------------------------------------------------------
-- Grants (authenticated + service_role; no anon table access)
-- ---------------------------------------------------------------------------

REVOKE ALL ON TABLE public.people FROM anon;
REVOKE ALL ON TABLE public.attendance FROM anon;
REVOKE ALL ON TABLE public.service FROM anon;
REVOKE ALL ON TABLE public.profiles FROM anon;

GRANT ALL ON TABLE public.people TO authenticated, service_role;
GRANT ALL ON TABLE public.attendance TO authenticated, service_role;
GRANT ALL ON TABLE public.service TO authenticated, service_role;
GRANT ALL ON TABLE public.profiles TO authenticated, service_role;

GRANT EXECUTE ON FUNCTION public.sync_people_auto_id_seq() TO service_role;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
